version: '3'
services:
    node_alice:
        image: wpank/polkadot-super-fast
        ports:
            - "30333:30333"
            - "9944:9944"
        volumes:
            - "polkadot-data-alice:/alice"
        command: polkadot --chain=polkadot-local --telemetry-url 'ws://172.28.1.4:8000/submit 0' --validator --unsafe-ws-external --rpc-methods Unsafe --unsafe-rpc-external --ws-port 9944 --rpc-cors all --pruning archive --alice --node-key aa788920201122290fc7d3faf00698d9a8e061d7173424da2a31a8130a882a5f
        depends_on:
            - telemetry-backend
            - mongo
            - 1kv
        networks:
            testing_net:
                ipv4_address: 172.28.1.1

    node_bob:
        image: wpank/polkadot-super-fast
        ports:
            - "30334:30334"
            - "9945:9945"
        volumes:
            - "polkadot-data-bob:/bob"
        command: polkadot --chain=polkadot-local --telemetry-url 'ws://172.28.1.4:8000/submit 0' --validator --unsafe-ws-external --ws-port 9945 --pruning archive --bob --bootnodes /ip4/172.28.1.1/tcp/30333/p2p/12D3KooWCJC43YRmb5WJcJmskPSxbkWY4Vp6jPKdFeggnXPxgBCw --port 30334
        depends_on:
            - telemetry-backend
            - mongo
            - 1kv
        networks:
            testing_net:
                ipv4_address: 172.28.1.2

    node_charlie:
        image: wpank/polkadot-super-fast
        ports:
            - "30336:30336"
            - "9946:9946"
        volumes:
            - "polkadot-data-bob:/bob"
        command: polkadot --chain=polkadot-local --telemetry-url 'ws://172.28.1.4:8000/submit 0' --validator --unsafe-ws-external --ws-port 9946 --pruning archive --charlie --bootnodes /ip4/172.28.1.1/tcp/30333/p2p/12D3KooWCJC43YRmb5WJcJmskPSxbkWY4Vp6jPKdFeggnXPxgBCw --port 30336
        depends_on:
            - telemetry-backend
            - mongo
            - 1kv
        networks:
            testing_net:
                ipv4_address: 172.28.1.3

    telemetry-backend:
        image: parity/substrate-telemetry-backend
        environment:
        - PORT=8000
        ports:
        - 8000:8000
        expose:
        - 8000
        command: --listen 0.0.0.0:8000
        networks:
            testing_net:
                ipv4_address: 172.28.1.4
    
    telemetry-frontend:
        image: parity/substrate-telemetry-frontend
        ports:
            - 3000:80
        environment:
            - SUBSTRATE_TELEMETRY_URL=ws://172.28.1.4:8000/feed 
        networks:
            testing_net:
                ipv4_address: 172.28.1.5

    mongo:
        image: mongo
        restart: always
        ports:
            - "27017:27017"
        networks:
            testing_net:
                ipv4_address: 172.28.1.6

    1kv:
        build: .
        ports:
            - "3300:3300"
        networks:
            testing_net:
                ipv4_address: 172.28.1.7

volumes:
    polkadot-data-alice:
    polkadot-data-bob:

networks:
    testing_net:
        ipam:
            driver: default
            config:
                - subnet: 172.28.0.0/16
