{{ if .Values.certificate.enabled }}
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Values.namespace }}
spec:
  secretName: {{ include "otv-backend.tls-secret-name" . }}
  issuerRef:
    name: letsencrypt
  dnsNames:
  - {{ include "otv-backend.backend-domain" . }}
  acme:
    config:
    - dns01:
        provider: prod-dns
      domains:
      - {{ include "otv-backend.backend-domain" . }}
{{ end }}
