environments:
  ci:
  local:
repositories:
  - name: bitnami
    url: https://raw.githubusercontent.com/bitnami/charts/archive-full-index/bitnami
releases:
  - name: kusama-mongodb
    namespace: kusama
    chart: bitnami/mongodb
    version: ^10.31.5
    values:
      - ./config/mongodb-common.yaml.gotmpl
  - name: polkadot-mongodb
    namespace: polkadot
    chart: bitnami/mongodb
    version: ^10.31.5
    values:
      - ./config/mongodb-common.yaml.gotmpl
