environments:
  production:
  ci:

repositories:
- name: w3f
  url: https://w3f.github.io/helm-charts/

releases:
{{ if eq .Environment.Name "production" }}
- name: kusama-otv-backend
  namespace: kusama
  chart: w3f/otv-backend
  version: v2.0.0
  values:
  - ./config/kusama/otv-backend.yaml.gotmpl
  
- name: polkadot-otv-backend
  namespace: polkadot
  chart: w3f/otv-backend
  version: v2.0.0
  values:
  - ./config/polkadot/otv-backend.yaml.gotmpl

{{ else }}
- name: otv-backend
  chart: ../charts/otv-backend
  values:
  - ./config/polkadot/otv-backend.yaml.gotmpl
{{ end }}