environments:
  production:
  ci:
repositories:
  - name: w3f
    url: https://w3f.github.io/helm-charts/
releases:
  - name: kusama-otv-mongo-express
    namespace: kusama
    chart: w3f/mongo-express
    version: v0.3.1
    values:
      - ./config/mongo-express-common.yaml.gotmpl
{{ if eq .Environment.Name "prod" }}
      - ./config/kusama/mongo-express-prod.yaml.gotmpl
{{ else }}
      - ./config/kusama/mongo-express-ci.yaml.gotmpl
{{ end }}
  - name: polkadot-otv-mongo-express
    namespace: polkadot
    chart: w3f/mongo-express
    version: v0.3.1
    values:
      - ./config/mongo-express-common.yaml.gotmpl
{{ if eq .Environment.Name "prod" }}
      - ./config/polkadot/mongo-express-prod.yaml.gotmpl
{{ else }}
      - ./config/polkadot/mongo-express-ci.yaml.gotmpl
{{ end }}
