environment: production

domain: w3f.community
dataPath: "/data"

namespace: default

backendPort: 3300

image:
  repo: web3f/otv-backend
  tag: latest

certificate:
  enabled: true

secret: |
  {
    "matrix": {
        "accessToken": "xxxxx"
    },
    "scorekeeper": {
        "nominators": []
    }
  }
